[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "emerald_hws"
version = "0.0.10"
dependencies = ["boto3", "awsiotsdk"]
authors = [{ name = "Ross Williamson", email = "ross@inertia.net.nz" }]
description = "A package to manipulate and monitor Emerald Heat Pump Hot Water Systems"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[project.urls]
"Homepage" = "https://github.com/ross-w/emerald_hws_py"
"Bug Tracker" = "https://github.com/ross-w/emerald_hws_py/issues"
